### PR TITLE
 Use TOC's for color in WAMI Viewer

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify `vtkVgTrackRepresentationBase` to support coloring by a track's TOC (rather than PVO), by using a `vtkVgTrackTypeRegistry` to supply the color information. Modify WAMI Viewer to use this mode. Modify `vdfTrackSource` so that `trackClassificationAvailable` can actually be emitted by track sources.

This deprecates most of the old PVO-based stuff in the representation, but does not yet remove it, as doing so would require non-trivial changes to some of the query video classes.

This is a recreation of #49, which GitHub somehow managed to butcher. It looks like the history/diffs should be more reasonable this time...

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
AFAICT, the `QStringList` thing [*should* compile](https://godbolt.org/z/Dca4Ep). What version of VS are you using? Is it feasible to just not support older than 2019?

**Comment by mwoehlke-kitware** [comment]
@RustyBlue, please see [my previous reply](/Kitware/vivia/pull/49#discussion_r404944976) at #49.

**Comment by RustyBlue** [comment]
Grrrr - I did see that, but was looking at the first part of my comment, thinking that was the part that was resolved..

I tried to build master - didn't get past running CMake:
```

CMake Error at CMake/functions.cmake:313 (file):
  file failed to open for writing (Invalid argument):

    C:/Vision/DIVA/vivia/build/include/VvVtkWidgets/vvVtkWidgets_autogen/include_$<CONFIG>/ui_videoQuery.h.tmp
```

Note, FWIW, I set `CMAKE_CONFIGURATION_TYPES` to `Release`

**Comment by RustyBlue** [comment]
As noted in my previous comment, I can't build the master branch - on Windows, using Visual Studio 2017.  So, building fails for this branch, both by itself or when merged with master.

Other than the build issues, I think this branch is ready to merge.

**Comment by mwoehlke-kitware** [comment]
> Other than the build issues, I think this branch is ready to merge.

Approved, then? (Note: please update your review if so.) Since the issue is already on master, I'm inclined to not hold this up (but please keep pestering me to fix the header issue!).

**Pull request merged**
