### PR TITLE
Update copyright banners

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update copyright banners and squash consecutive blank lines. These are combined because the script being used does both in order to ensure that replacing the banner doesn't inadvertently insert consecutive blanks.

Some of these changes (particularly, in CMake and Python files) have been made by hand, as the script only handles C/C++ sources. Also, remove the old insert-copyright.pl script (that we appear to have inherited from VidTK).

### CODE REVIEW

**Review by RustyBlue — APPROVED** [review]
I'm not confirming the correctness of the license info - but "assuming" is is correct, I approve of this change.

**Comment by mwoehlke-kitware** [comment]
I'm not sure what you're assuming? It's pretty easy to verify that https://github.com/Kitware/vivia/blob/master/LICENSE is a working link, and, well, if those contents are wrong, they've been wrong for some time. Do you just mean you didn't skim the actual changes for weirdness?

(The new banners all have the same text, hopefully you at least looked at one example?)

**Comment by RustyBlue** [comment]
I was referring to specification of

> OSI-approved BSD 3-Clause License

**Comment by mwoehlke-kitware** [comment]
Ah... a.k.a. [this](https://opensource.org/licenses/BSD-3-Clause). I checked; it's the same as our [`LICENSE`](https://github.com/Kitware/vivia/blob/master/LICENSE), modulo that "the copyright holder" is replaced with "Kitware, Inc.".

**Pull request merged**
